 CREATE TABLE "SGS"."T_LOG_PARAMETROS" 
   (	"FECHA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"USUARIO" VARCHAR2(20 BYTE) DEFAULT USER NOT NULL ENABLE, 
	"PARAMETRO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"VALOR_NUEVO" VARCHAR2(100 BYTE), 
	"VALOR_VIEJO" VARCHAR2(100 BYTE)
   ) ;