UPDATE kanban.t_premios SET ESPECIE=93 where sorteo=4910 and ID_SORTEO_ANTICIPADO =5111 AND ESPECIE IS NULL;
UPDATE kanban.t_premios SET ESPECIE=93 where sorteo=4910 and ID_SORTEO_ANTICIPADO =5091 AND ESPECIE IS NULL;
UPDATE kanban.t_premios SET ESPECIE=98 where sorteo=4910 and ID_SORTEO_ANTICIPADO =5012 AND ESPECIE IS NULL;
UPDATE kanban.t_premios SET ESPECIE=98 where sorteo=4910 and ID_SORTEO_ANTICIPADO =5092 AND ESPECIE IS NULL;