CREATE OR REPLACE PROCEDURE "PR_TT_NUEVO_SORTEO_ENTERO_F_A"
(
  P_ID_JUEGO IN NUMBER,
  P_SORTEO IN NUMBER,
  P_POSICION  IN NUMBER,
  P_ZONA_JUEGO  IN NUMBER,
  P_SEMANA IN NUMBER,
  P_ORDEN IN NUMBER
)
IS
  V_ALEATORIO NUMBER;
  V_DESDE     NUMBER;
  V_HASTA     NUMBER;
  V_EXISTE  NUMBER:=0;
  V_EXISTE_GANADOR_SEMANA  NUMBER:=1;
  V_ESPECIA VARCHAR2(100);
  V_ID_ESPECIAL NUMBER;
  V_SORTEO NUMBER;
  V_MAX_ORDEN NUMBER;
  V_PROGRESION NUMBER;
  V_FRACCION NUMBER;
  V_CANTIDAD_FRACCION NUMBER;
  
  V_MODALIDAD VARCHAR2(100);
  
  
  V_AGENCIA NUMBER;
  V_LOCALIDAD VARCHAR2(200);
  V_SUCURSAL VARCHAR2(200);
  V_DESCRIPCION_AGENCIA VARCHAR2(200);
  V_PROVINCIA VARCHAR2(200);
  
  V_CANTIDAD_SORTEOS NUMBER;
  V_CANTIDAD_PARTICIPANTES NUMBER;
  V_CANTIDAD_GANADORES NUMBER;
  
BEGIN
/**
 *
 * Anticipados busqueda de ganador
 *
 * @author     Emmanuel Quattropani<emma.nuel.quattropani@loteriacba.com.ar>
 * Date: 16/05/2017: 
 * (1)Se arregla para no tener fijo el maximo de fra222333ccion, además se corrigen
 * los filtros en la tabla billetes participantes por sorteo y juego, 
 * (2)Validacion que el sorteo tenga billetes importados
 * 
 */
  V_EXISTE :=0;
  V_DESDE:=NULL;
  V_HASTA:=NULL;
  BEGIN
    SELECT SORTEO
    INTO V_SORTEO
    FROM T_BILLETES_PARTICIPANTES  
    WHERE ROWNUM=1
    AND SORTEO= P_SORTEO
    AND ID_JUEGO= P_ID_JUEGO;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR( -20001, 'No existen fracciones importadas' );

  END;
  SELECT MIN(BILLETE),MAX(BILLETE)
  INTO V_DESDE,V_HASTA
  FROM T_BILLETES_PARTICIPANTES
    WHERE SORTEO= P_SORTEO
  AND ID_JUEGO= P_ID_JUEGO;
  
  IF V_DESDE IS NULL AND V_HASTA IS NULL THEN
   RAISE_APPLICATION_ERROR( -20001, 'No existen fracciones importadas' );
  END IF;
  
  SELECT FRACCIONES
  INTO V_CANTIDAD_FRACCION
  FROM T_SORTEO
    WHERE SORTEO= P_SORTEO
  AND ID_JUEGO= P_ID_JUEGO;
  
  

SELECT
    COUNT(*) INTO V_CANTIDAD_SORTEOS
FROM
    T_ANTICIPADA
    WHERE SORTEO=P_SORTEO
    AND ID_JUEGO=P_ID_JUEGO
    AND SEMANA=P_SEMANA;
  
  
SELECT COUNT(*) INTO V_CANTIDAD_PARTICIPANTES
    FROM T_BILLETES_PARTICIPANTES  
    WHERE  SORTEO= P_SORTEO
    AND ID_JUEGO= P_ID_JUEGO;
   
   
   SELECT
    COUNT(*) INTO V_CANTIDAD_GANADORES
FROM
    T_ANTICIPADA_GANADORES
    WHERE SORTEO=P_SORTEO
    AND ID_JUEGO=P_ID_JUEGO
    AND SEMANA=P_SEMANA; 
    
 IF V_CANTIDAD_PARTICIPANTES<V_CANTIDAD_SORTEOS  THEN
   RAISE_APPLICATION_ERROR( -20001, 'No hay participantes suficientes para sortear' );
  END IF;
  
  
   IF V_CANTIDAD_GANADORES = V_CANTIDAD_SORTEOS  THEN
   RAISE_APPLICATION_ERROR( -20001, 'Ya han sido sorteados los' ||V_CANTIDAD_SORTEOS||' premios de la semana' );
  END IF;
  
  V_EXISTE_GANADOR_SEMANA  :=1;
  
  WHILE V_EXISTE_GANADOR_SEMANA=1 LOOP
    --ALEATORIO DENTRO DE LOS PARAMETROS
    
        SELECT BILLETE,FRACCION INTO V_ALEATORIO,V_FRACCION  FROM (
          SELECT  BILLETE,FRACCION
          FROM T_BILLETES_PARTICIPANTES
            WHERE SORTEO= P_SORTEO
            AND ID_JUEGO= P_ID_JUEGO
          ORDER BY DBMS_RANDOM.VALUE
        )WHERE ROWNUM=1  ;
   
    --VERIFICO QUE NO ALLA GANADOr EN ESTA SEMANA
    BEGIN    
      SELECT 1 INTO V_EXISTE_GANADOR_SEMANA
    FROM
        SGS.T_ANTICIPADA_GANADORES 
    WHERE BILLETE = V_ALEATORIO
    AND FRACCION = V_FRACCION
    AND SORTEO= P_SORTEO
    AND ID_JUEGO= P_ID_JUEGO
    AND SEMANA= P_SEMANA
    AND ROWNUM  = 1;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        V_EXISTE_GANADOR_SEMANA:= 0;
    END;
    
  
  END LOOP;
  	
	SELECT NVL(MAX(ORDEN),0)
      INTO V_MAX_ORDEN
      FROM SGS.T_EXTRACCION
      WHERE ID_JUEGO  = P_ID_JUEGO
      AND SORTEO      = P_SORTEO
      AND ZONA_JUEGO  = P_ZONA_JUEGO;
  
	SELECT 
		ID_AGENCIA,
		NVL(LOCALIDAD,PROVINCIA),
		DESCRIPCION_AGENCIA,
		PROVINCIA,
    MODALIDAD,
    DESCRIPCION_SUCURSAL
	INTO
		V_AGENCIA,
		V_LOCALIDAD,
		V_DESCRIPCION_AGENCIA,
		V_PROVINCIA,
    V_MODALIDAD,
    V_SUCURSAL
	FROM T_BILLETES_PARTICIPANTES WHERE BILLETE = V_ALEATORIO
    AND FRACCION = V_FRACCION
    AND SORTEO = P_SORTEO
    AND ID_JUEGO = P_ID_JUEGO;
    
    IF V_MODALIDAD = 'VENTA CONTADO CASA CENTRAL' THEN
      V_DESCRIPCION_AGENCIA := 'VENTA CONTADO CASA CENTRAL';      
    END IF;
  
    IF V_MODALIDAD = 'VENTA CONTADO' THEN
      V_DESCRIPCION_AGENCIA := 'VENTA CONTADO';      
    END IF;
	
	INSERT INTO SGS.T_ANTICIPADA_GANADORES (ID_JUEGO,    SORTEO,    SEMANA,    BILLETE,    FRACCION,    AGENCIA,    LOCALIDAD, NOMBRE, ORDEN,SUCURSAL)
	VALUES  (P_ID_JUEGO,P_SORTEO,P_SEMANA,V_ALEATORIO,V_FRACCION,V_AGENCIA,V_LOCALIDAD,V_DESCRIPCION_AGENCIA, P_ORDEN,V_SUCURSAL);
	
END PR_TT_NUEVO_SORTEO_ENTERO_F_A;